name: ci

on:
  workflow_dispatch:
  push:

env:
  DOCKER_REPOSITORY: harzu
  APP_NAME: gotest

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout code from master
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38

  system_test:
    runs-on: "ubuntu-latest"
    needs: lint
    steps:
    - name: checkout code from master
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: build helper
      uses: ./.github/actions/helper
      with:
        docker_repository: $DOCKER_REPOSITORY
        app_name: $APP_NAME
        version: ${{ github.sha }}
        token: ${{ secrets.TOKEN }}
      
    - name: run tests
      env:
        VERSION: ${{ github.sha }}
      run: make test-ci

    - name: cleanup
      if: always()
      env:
        VERSION: ${{ github.sha }}
      run: make stop
        