name: ci

on:
  workflow_dispatch:
  push:

env:
  HELPER_TAG: harzu/gotest-helper

jobs:
  prebuild:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout code from master
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: build helper image
        run: docker build --no-cache --pull -f ./build/helper.ci.Dockerfile -t $HELPER_TAG:$GITHUB_SHA --build-arg CI_JOB_TOKEN=${{ secrets.TOKEN }} .
  # lint:
  #   needs: prebuild
  # unit:
  #   needs: prebuild
  # system:
  #   needs: unit
